import {
  ASSISTANT_PROGRESS_10_MESSAGES,
  ASSISTANT_PROGRESS_50_MESSAGES,
  ASSISTANT_PROGRESS_90_MESSAGES,
} from '../lib/diary-messages';

export const INACTIVE_TEXT_LEN = 32;

export const ASSISTANT_PROGRESS_MESSAGES = {
  10: ASSISTANT_PROGRESS_10_MESSAGES,
  50: ASSISTANT_PROGRESS_50_MESSAGES,
  90: ASSISTANT_PROGRESS_90_MESSAGES,
} satisfies Record<number, string[]>;
